### ISSUE TITLE
Version update

### ISSUE THREAD

**Issue by shybovycha** [stationkeeping/bootstrap-slider-rails#7] opened 2014-10-08 11:29 UTC
Could you, please, publish the new gem version to the RubyGems repository? The one there is `1.9.0` and the one here is `4.0.9`.

**Comment by zedtux** [comment] 2015-03-22 11:15
Please publish a new version of the gem

**Comment by fredngo** [comment] 2015-05-31 10:17
+1, please publish a new version.

**Comment by zedtux** [comment] 2015-05-31 11:19
I have a fork over here with the latest version : https://github.com/YourCursus/bootstrap-slider-rails.

You can use it as the following:

    gem 'bootstrap-slider-rails', github: 'YourCursus/bootstrap-slider-rails'

**Comment by fredngo** [comment] 2015-05-31 13:34
@zedtux For me, the problem is I cannot embed a github reference into a gem! All dependencies in a gem must be released. See http://stackoverflow.com/questions/6499410/ruby-gemspec-dependency-is-possible-have-a-git-branch-dependency

@stationkeeping please publish a new version!

**Comment by Undistraction** [comment] 2015-05-31 13:49
Sorry all. This is not something I have time for any more. I would be happy to add someone to this repo, or retire this gem so one of you can own it - whatever would be of most use to users.

**Comment by zedtux** [comment] 2015-05-31 16:34
@Undistraction in the case you remove your gem from rubygem I could then push my version. I'm using the library in my project which is for a startup so I will have to maintain the gem anyway which should solve the @fredngo's issue and also for all the others of this thread.

**Comment by Undistraction** [comment] 2015-05-31 17:49
No problem. I'll pull it tomorrow.

**Comment by zedtux** [comment] 2015-05-31 17:51
Thank you. Just let me know when it's done.

**Comment by Undistraction** [comment] 2015-06-01 19:09
@zedtux Not sure what the best way to do this is. People will have projects using this gem in its current form. If I add you as an [owner](http://guides.rubygems.org/command-reference/#gem-owner) – please PM me the email you want to use – then you can push directly from your fork and I will just delete this version. Does that make sense?

**Comment by zedtux** [comment] 2015-06-01 20:52
@Undistraction why not, it's a good idea.

**Comment by Undistraction** [comment] 2015-06-02 17:06
@zedtux I've added you as an owner. Let me know here if you have any issues.

**Comment by zedtux** [comment] 2015-06-02 18:13
Thank you @Undistraction. I will push my version by tomorrow.

**Comment by zedtux** [comment] 2015-06-03 14:19
@Undistraction it's working fine !

@shybovycha @kamisama @fredngo the new version has been pushed ! @Undistraction you can close the issue.

**Comment by Undistraction** [comment] 2015-06-03 14:21
@zedtux Nicely done

**Closed by Undistraction** 2015-06-03 14:21 UTC

**Comment by zedtux** [comment] 2015-06-03 16:43
Here is the link : https://github.com/YourCursus/bootstrap-slider-rails. Maybe you'll have to update it in the gemspec file so that clicking the "Homepage" (or "Source code" would make more sense) from rubygems.org would redirect to my fork, don't you think ?

**Comment by Undistraction** [comment] 2015-06-03 16:55
@zedtux You should be able to update it in your own fork's Gemspec.

**Comment by zedtux** [comment] 2015-06-03 16:56
@Undistraction mmm you're right, I haven't though about it, I will try it.

**Comment by fredngo** [comment] 2015-06-05 09:29
@zedtux Thanks! I'll try it as soon as I can.

**Comment by zedtux** [comment] 2015-06-05 14:50
FYI it's working fine in my project so I don't expect issues for you guys but in the case you would have one, feel free to open an issue [here](https://github.com/YourCursus/bootstrap-slider-rails/issues).
